approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.14.1.cjs
